---
# file: playbook.yml

- hosts: all
  connection: local
  gather_facts: no

  roles:
  - app_a

  tasks:
  - debug:
      msg: |
        {{ vars | to_nice_json }}
      verbosity: 2

  - copy:
      dest: /tmp/{{ out_file }}
      content: "{{ vars | to_nice_json }}"
